version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    environment:
      - MODX_DB_HOST=db
      - MODX_DB_USER=modx
      - MODX_DB_PASSWORD=modx
      - MODX_DB_NAME=modx

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modx
      MYSQL_USER: modx
      MYSQL_PASSWORD: modx
    ports:
      - "3306:3306"
