services:
  victim:
    build: ./victim
    container_name: victim
    ports:
      - "5000:5000"

  attacker:
    build: ./attacker
    container_name: attacker
    ports:
      - "8080:80"
    depends_on:
      - victim
